CREATE TABLE `store` (
  `no` int NOT NULL COMMENT 'no',
  `shopname` varchar(50) NOT NULL COMMENT '상가명',
  `localname` varchar(30) NOT NULL COMMENT '지역명',
  `code1` varchar(30) DEFAULT NULL COMMENT '대분류코드',
  `codename` varchar(30) DEFAULT NULL COMMENT '대분류명',
  `code2` varchar(30) DEFAULT NULL COMMENT '중분류코드',
  `codename2` varchar(30) DEFAULT NULL COMMENT '중분류명',
  `code3` varchar(30) DEFAULT NULL COMMENT '소분류코드',
  `codename3` varchar(30) DEFAULT NULL COMMENT '소분류명',
  `code4` varchar(30) DEFAULT NULL COMMENT '표준산업분류코드',
  `codename4` varchar(30) DEFAULT NULL COMMENT '표준산업분류명',
  `citycode` varchar(30) NOT NULL COMMENT '시도코드',
  `city` varchar(30) NOT NULL COMMENT '시도명',
  `gucode` varchar(30) NOT NULL COMMENT '시군구코드',
  `gu` varchar(30) NOT NULL COMMENT '시군구명',
  `dongcode` varchar(30) NOT NULL COMMENT '동코드',
  `dong` varchar(30) NOT NULL COMMENT '동명',
  `jibuaddress` varchar(50) NOT NULL COMMENT '지번주소',
  `address` varchar(50) DEFAULT NULL COMMENT '도로명주소',
  `oldpostcode` varchar(30) DEFAULT NULL COMMENT '구우편번호',
  `postcode` varchar(30) NOT NULL COMMENT '우편번호',
  `lng` varchar(30) NOT NULL COMMENT '경도',
  `lat` varchar(30) NOT NULL COMMENT '위도',
  PRIMARY KEY (`no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci